version: '3'

services:
    frontend:
      build: ./frontend
      restart: always
      volumes:
        - /app/node_modules # исключение папки контейнера из переопределения ниже (т.к. в папке ./frontend нету node_modules
        - ./frontend:/app   # подключение внешней папки приложения (в Windows) в качестве папки для контейнера
      ports:
        - '3000:3000' # если порты разные, то будет проблема с webSocket, связана она с hot-reload.
    api:
      build: ./api
      restart: always
      volumes:
        - /app/node_modules # исключение папки контейнера из переопределения ниже (т.к. в папке ./frontend нету node_modules
        - ./api:/app        # подключение внешней папки приложения (в Windows) в качестве папки для контейнера
      depends_on:
        - mysql
      environment:  # эти переменные средЫ появятся в процессе при запуске, и Нода их считает в файле ./api/src/utils/mysqlPool.mjs
        MYSQL_HOST: mysql
        MYSQL_PORT: '3306'
        MYSQL_USER: root
        MYSQL_PASSWORD: password
        MYSQL_DB: time_db
      ports:
        - '5555:5000'
    mysql:
      image: mysql
      restart: always
      environment:  # а эти переменные средЫ, видимо, нужны для контейнера mysql
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: time_db
      volumes:
        - mysql_data:/var/lib/mysql
    adminer:
      image: adminer
      restart: always
      ports:
        - '8888:8080'
volumes:
  mysql_data:
