version: '3'

services:
    frontend:
      image: dimanvaz/time-app-frontend-dev
      restart: always
      ports:
        - '3000:3000' # если порты разные, то будет проблема с webSocket, связана она с hot-reload.
    api:
      image: dimanvaz/time-app-api-dev
      restart: always
      depends_on:
        - mysql
      environment:  # эти переменные средЫ появятся в процессе при запуске, и Нода их считает в файле ./api/src/utils/mysqlPool.mjs
        MYSQL_HOST: mysql
        MYSQL_PORT: '3306'
        MYSQL_USER: root
        MYSQL_PASSWORD: password
        MYSQL_DB: time_db
      ports:
        - '5555:5000'
    mysql:
      image: mysql
      restart: always
      environment:  # а эти переменные средЫ, видимо, нужны для контейнера mysql
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: time_db
      volumes:
        - mysql_data_pub:/var/lib/mysql
    adminer:
      image: adminer
      restart: always
      ports:
        - '8888:8080'
volumes:
  mysql_data_pub:
